# Generated by Django 5.2.1 on 2025-05-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
    ]
